name: 'gi_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'gi_lakehouse'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  gi_lakehouse:
    staging:
      +materialized: view
      +schema: stg
    gold_commercial:
      +materialized: table
      +schema: gld_commercial
    gold_performance:
      +materialized: table
      +schema: gld_performance
    gold_clients:
      +materialized: table
      +schema: gld_clients
    gold_staffing:
      +materialized: table
      +schema: gld_staffing

vars:
  cout_gestion_pct: 0.05
  churn_seuil_high_jours: 90
  churn_seuil_medium_jours: 45
